from .text_to_word import (
    NODE_CLASS_MAPPINGS as WORD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WORD_NODE_DISPLAY_NAME_MAPPINGS,
)
from .srt_node import (
    NODE_CLASS_MAPPINGS as SRT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SRT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(WORD_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SRT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(WORD_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SRT_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
